# Generated by Django 4.1.2 on 2022-11-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ish', models.CharField(max_length=200)),
                ('rot', models.IntegerField()),
                ('zac', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='rot',
            field=models.IntegerField(),
        ),
    ]
