# Generated by Django 4.1.2 on 2022-11-01 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0002_unmessage_alter_message_rot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.CharField(default=datetime.date, max_length=200),
        ),
    ]
