# Generated by Django 4.1.2 on 2022-11-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0004_alter_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
