# Generated by Django 4.1.2 on 2022-11-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0005_remove_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.CharField(default='2022111', max_length=200),
        ),
    ]
